MODEL:
  META_ARCHITECTURE: "Distillation"
  BACKBONE:
    NAME: "build_mobilenetv2_fpn_backbone"
  MOBILENETV2:
    OUT_FEATURES: ["m2", "m3", "m4", "m5"]
  FPN:
    IN_FEATURES: ["m2", "m3", "m4", "m5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 11
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
DATASETS:
  TRAIN: ("doc_train",)
  TEST: ("doc_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (224,)
TEACHER:
  MODEL:
    META_ARCHITECTURE: "GeneralizedRCNN"
    PIXEL_MEAN: [123.675, 116.280, 103.530]
    PIXEL_MEAN: [123.675, 116.280, 103.530]
    WEIGHTS: "/data2/users/abanerjee/distill_vitb/model_final.pth"
    MASK_ON: False
    BACKBONE:
      NAME: "build_vit_fpn_backbone"
    VIT:
      ARCH: 'vit_base_patch16_224'
      OUT_FEATURES: ["layer3", "layer5", "layer7", "layer11"]
      DROP_PATH: 0.1
      IMG_SIZE: 224
      PATCH_SIZE: 16
    FPN:
      IN_FEATURES: ["layer3", "layer5", "layer7", "layer11"]
    ANCHOR_GENERATOR:
      SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
      ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
    PROPOSAL_GENERATOR:
      NAME: "TeacherRPN"
    RPN:
      IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
      PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
      PRE_NMS_TOPK_TEST: 1000  # Per FPN level
      # Detectron1 uses 2000 proposals per-batch,
      # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
      # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
      POST_NMS_TOPK_TRAIN: 1000
      POST_NMS_TOPK_TEST: 1000
    ROI_HEADS:
      NAME: "TeacherROIHeads"
      IN_FEATURES: ["p2", "p3", "p4", "p5"]
      NUM_CLASSES: 11
    ROI_BOX_HEAD:
      NAME: "FastRCNNConvFCHead"
      NUM_FC: 2
      POOLER_RESOLUTION: 7
    ROI_MASK_HEAD:
      NAME: "MaskRCNNConvUpsampleHead"
      NUM_CONV: 4
      POOLER_RESOLUTION: 14
  DATASETS:
    TRAIN: ("doc_train",)
    TEST: ("doc_val",)
  SOLVER:
    IMS_PER_BATCH: 16
    BASE_LR: 0.02
    STEPS: (60000, 80000)
    MAX_ITER: 90000
  INPUT:
    MIN_SIZE_TRAIN: (224,)

VERSION: 2