_BASE_: "Base-Distillation-ViT.yaml"
OUTPUT_DIR: output/distillationtmp
MODEL:
  META_ARCHITECTURE: "Distillation"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone_kd"
  WEIGHTS: "projects/Distillation/pretrained/r50.pth"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 101
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "DistillRPN"
  ROI_HEADS:
    NAME: "DistillROIHeads"
    NUM_CLASSES: 11

TEACHER:
  MODEL:
    VIT:
      ARCH: 'vit_base_patch16_224'
      OUT_FEATURES: ["layer3", "layer5", "layer7", "layer11"]
      DROP_PATH: 0.1
      IMG_SIZE: 224
      PATCH_SIZE: 16

DATASETS:
  TRAIN: ("doc_train",)
  TEST: ("doc_val",)

TEST:
  EVAL_PERIOD: 2000

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  MAX_ITER: 180000
  STEPS:
  - 120000
  - 160000

KD:
  FEATURE_ON: False
  FEATURE_LOSS_WEIGHT: 0.5
  REGION_CORRELATION_LOSS_ON: True
  REGION_CORRELATION_LOSS_USE_BG_FEATURE: True
  REGION_CORRELATION_LOSS_WEIGHT_POOL: 1.0
  REGION_CORRELATION_POOL_LOSS: True
  FEATURE_ROIPOOL_FG_LOSS_ON: True
  FEATURE_ROIPOOL_FG_LOSS_WEIGHT: 0.5
  FEATURE_ROIPOOL_BG_LOSS_ON: True
  FEATURE_ROIPOOL_BG_LOSS_WEIGHT: 0.5
  USE_BG_FEATURE_MINING_THRS: True
  BG_MINING_THRS: 0.6
  BG_FEATURE_MINING_ON: True
  USE_BG_WEIGHT_SCALE: True
  BG_WEIGHT_ALPHA: 7.5
